# Site settings
title: Baking code by cookiesthatimade ðŸª
subtitle: From dough to deploy â€“ handcrafted full-stack projects | ë°˜ì£½(dough)ë¶€í„° ë°°í¬(deploy)ê¹Œì§€, ì •ì„±ê» ìˆ˜ìž‘ì—…ìœ¼ë¡œ ë§Œë“  í’€ìŠ¤íƒ í”„ë¡œì íŠ¸ë“¤
email: hosh2326@naver.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "/cookiesthatimade.github.io" # the base hostname & protocol for your site

github_username: cookiesthatimade
linkedin_username: cookiesthatimade

# Build settings
markdown: kramdown
